### ISSUE TITLE
Make editions that install the regular alpine packages

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/alpine-lima#107]
I made some "editions" of alpine-lima, that installs the regular packages:

* ~~#34~~
* ~~#43~~
* ~~#45~~

These apk are now available upstream, making the installation smoother.

----

Only added some refactoring, to make using "nerdctl-full" more explicit:

* #105
* #106

To make "nerdctl" mean _only_ nerdctl, and call the bundle "nerdctl-full"

**Comment by afbjorklund** [comment]
I'm not sure you want the actual editions in the main project:

https://github.com/afbjorklund/alpine-lima/tree/editions

Just adding the knobs and options, to make them possible...

```
export LIMA_INSTALL_NERDCTL_FULL=false

export LIMA_INSTALL_NERDCTL=false
export LIMA_INSTALL_PODMAN=false
export LIMA_INSTALL_DOCKER=false
```

**Comment by afbjorklund** [comment]
Basically these editions are a merge of template://alpine and *-rootful

Might include nerdctld for the nerdctl.sock, haven't decided (an option)

**Comment by jandubois** [comment]
@afbjorklund Is this still the plan? Is there a point in maintaining these as ISO editions when the user could just use the regular image template and install the additional packages with `apk`?

Unless you plan to create and maintain the additional editions, I would suggest we close this issue.

**Comment by afbjorklund** [comment]
It is not something that I would be maintaining, so it can be scripted on top of alpine unless someone else does it...
