### ISSUE TITLE
Bump to Alpine 3.19

### ISSUE THREAD

**Issue by jandubois** [lima-vm/alpine-lima#116]
Alpine 3.19 has been released earlier this month and includes newer versions of `containerd` and `docker`.

This should be a minimal change:

```diff
--- Makefile
+++ Makefile
@@ -1,4 +1,4 @@
-ALPINE_VERSION ?= 3.18.0
+ALPINE_VERSION ?= 3.19.0
 REPO_VERSION ?= $(shell echo "$(ALPINE_VERSION)" | sed -E 's/^([0-9]+\.[0-9]+).*/v\1/')
```

Unfortunately this breaks `ssh` support in Lima:

```console
$ make EDITION=std lima
ALPINE_VERSION=3.19.0 EDITION=std ARCH=x86_64 ./lima.sh
WARN[0000] Ignoring non-existent instance "std"
[...]
INFO[0001] SSH Local Port: 40022
INFO[0001] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0029] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0039] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0049] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
INFO[0059] [hostagent] Waiting for the essential requirement 1 of 4: "ssh"
```

Using the QEMU display running `ssh -vvvv localhost` from inside the VM works just fine (I think, I didn't actually generate a key to login, but I see all the ssh logging and eventually the password prompt).

**Comment by afbjorklund** [comment]
I get: `unable to open config for system login`, from PAM (_pam_load_conf_file) in syslog

**Comment by afbjorklund** [comment]
Linking `system-login` to `login` makes the ssh connection work, not sure what you need?

**Comment by jandubois** [comment]
> [alpinelinux/aports@bb00d97](https://github.com/alpinelinux/aports/commit/bb00d972ea71fb52f3486df0badb475de6160404) removed /etc/pam.d/system-login
> 
> [alpinelinux/aports@8bc65a7](https://github.com/alpinelinux/aports/commit/8bc65a7e38eb29e22cb07f2f896b6ea290b18834) added /etc/pam.d/sshd

Thanks for the research! Looks like PAM configuration works now out-of-the-box.
