### ISSUE TITLE
aarch64 version

### ISSUE THREAD

**Issue by abiosoft** [lima-vm/alpine-lima#26]
I would like to know if there is anything else to consider with making an aarch64 version of this image.

I was able to build the aarch64 version and everything looks fine. Though the `syslinux` package is not available but it works fine without it.

Can I go ahead and create a PR?

**Comment by jandubois** [comment]
> Can I go ahead and create a PR?

Yes, please! I was planning to look into building an `aarch64` image in the near future anyways, so a PR would be very welcome.

I'm not sure what the significance of the `syslinux` package is; I probably copied that from somewhere else...
