### ISSUE TITLE
Make APKBUILD for buildkit

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/alpine-lima#37]
From https://github.com/lima-vm/alpine-lima/issues/34#issuecomment-1004758942

This would allow just doing `apk add buildkit`, with init script and all.

It would also move the files, from `/usr/local/bin` to `/usr/bin`.

Like for [containerd](https://git.alpinelinux.org/aports/tree/community/containerd?h=3.14-stable) today.

**Comment by afbjorklund** [comment]
This new package would preferrably go upstream, into community aports.

**Comment by afbjorklund** [comment]
Initial attempt:

https://github.com/afbjorklund/aports/commit/5e49ee893da8977c6f847cd5ac0077a020840e21

Based on:

https://github.com/alpinelinux/aports/commit/f1a5664f9f754c7898d4a411ffeff7a156457678

**Comment by afbjorklund** [comment]
It might have to go into "testing" before it can go into "community" ?

It also might need to go to https://gitlab.alpinelinux.org/alpine/aports

**Comment by jandubois** [comment]
Is there a way to build and use the package locally for testing? So that we can have an `nc` edition before upstream has a package for buildkitd?

**Comment by afbjorklund** [comment]
I think it can be done with a suitable Dockerfile, but I haven't tried it yet (just wrote it "blind", from containerd). Some `abuild` ?

https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package

**Comment by afbjorklund** [comment]
https://pkgs.alpinelinux.org/packages?name=buildkit&branch=v3.17
