### ISSUE TITLE
Make APKBUILD for nerdctl

### ISSUE THREAD

**Issue by afbjorklund** [lima-vm/alpine-lima#46]
Similar to:
* #37

For running:

`apk add nerdctl`

----

From https://github.com/lima-vm/alpine-lima/issues/34#issuecomment-1019119909

**Comment by afbjorklund** [comment]
There are pros and cons, regarding bundling the container runtime with the operating system image.

When installing it afterwards (like lima), then it might be easier (or faster) to update the nerdctl version.

But it would be "nice to have" both ?

**Comment by AkihiroSuda** [comment]
Yes, we should have the apk  in the upstream

**Comment by afbjorklund** [comment]
I think that `nerdctl` would be similar to other small go programs, like `runc`.

https://github.com/alpinelinux/aports/blob/3.14-stable/community/runc/APKBUILD

**Comment by afbjorklund** [comment]
Work in progress:

* https://github.com/afbjorklund/aports/tree/nerdctl/community/nerdctl/APKBUILD

* https://github.com/afbjorklund/aports/blob/buildkit/community/buildkit/APKBUILD
* https://github.com/afbjorklund/aports/blob/cni-plugin-isolation/community/cni-plugin-isolation/APKBUILD

**Comment by afbjorklund** [comment]
https://pkgs.alpinelinux.org/packages?name=nerdctl&branch=v3.17
