### ISSUE TITLE
Move to Alpine 3.16

### ISSUE THREAD

**Issue by jandubois** [lima-vm/alpine-lima#66]
To bump `containerd` from 1.5.11 to 1.6.4

**Comment by afbjorklund** [comment]
It seems like nerdctl is now in "testing", but no buildkit just yet (I should submit it).

https://pkgs.alpinelinux.org/packages?name=nerdctl

* https://github.com/lima-vm/alpine-lima/issues/46

* https://github.com/lima-vm/alpine-lima/issues/37
