### ISSUE TITLE
Let Lima install nerdctl instead of bundling it in the ISO

### ISSUE THREAD

**Issue by jandubois** [lima-vm/alpine-lima#77]
That's how it works for all other distros, and it allows updating of `nerdctl` without making a new alpine-lima release.

At the very least Lima should be able to update `nerdctl` to a newer version, even if the ISO already includes an older version.

**Comment by AkihiroSuda** [comment]
The following binaries are dynamically linked with glibc (as of nerdctl-full v0.22.0)
- buildg
- containerd
- containerd-stargz-grpc
- ctr
- ctr-remote
- ipfs

**Comment by jandubois** [comment]
> The following binaries are dynamically linked with glibc (as of nerdctl-full v0.22.0)

That's ok; the only binaries from the nerdctl tarball we install right now are `buildctl`, `buildkitd`, and `nerdctl`: https://github.com/lima-vm/alpine-lima/blob/034d4745e9aae32e6128e55696417dbe1e27ec40/genapkovl-lima.sh#L241-L244

So just being able to upgrade these 3 via lima would already be an advantage.

**Comment by afbjorklund** [comment]
All 3 binaries are now available in Alpine 3.17

**Comment by afbjorklund** [comment]
```console
lima-std:~$ nerdctl version
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/ 
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/ 
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/ 
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/ 
lima-std:~$ sudo nerdctl version
Client:
 Version:	1.0.0
 OS/Arch:	linux/amd64
 Git commit:	<unknown>
 buildctl:
  Version:	0.10.6
  GitCommit:	alpine

Server:
 containerd:
  Version:	v1.6.12
  GitCommit:	a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:	1.1.4
  GitCommit:	5fd4c4d144137e991c4acebb2146ab1483a97925

```

**Comment by terev** [comment]
Hello :D . Is this possible yet? Noticed that buildkitd is out of date and it's currently bundled with nerctl. Was hoping to use the new attestation features.

**Comment by afbjorklund** [comment]
I don't think that the nerdctl distribution ("nerdctl-full") comes in a musl flavor yet, it only supports glibc as far as I know

**Comment by jandubois** [comment]
#130 removes the setting to install `nerdctl` into the ISO image.

Getting Lima to install `nerdctl` into Alpine would have to be implemented in the Lima repo itself: https://github.com/lima-vm/lima/issues/2807

**Comment by afbjorklund** [comment]
Most likely it would need nerdctl to make a special build of the nerdctl-full distribution, for musl (not glibc)
